//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 16/04/2023
//  @ Author : 
//
//




/** */
public abstract class Player {
	/** */
	protected Inventory inventory;
	
	/** */
	protected NetworkElement position;
	
	/** */
	public void move(NetworkElement ne) {
	}
	
	/** */
	public void directPump() {
	}
	
	/** */
	public abstract void takePump(Inventory inv);
	
	/** */
	public abstract void placePump();
	
	/** */
	public abstract void connectPipe();
	
	/** */
	public abstract void disconnectPipe(NetworkElement ne);
	
	/** */
	public void setPosition(NetworkElement ne) {
	}
}
