//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 16/04/2023
//  @ Author : 
//
//


public abstract class Player {
	protected Inventory inventory;
	protected NetworkElement position;
	protected boolean stuck;
	protected int stuckTimeLeft;

	/** */
	public Player() {
		Proto.print("Player.Player()");
		position = null;
		stuck = false;
		stuckTimeLeft = 0;
		inventory = new Inventory(this);
	}

	/** */
	public Player(NetworkElement ne) {
		Proto.print("Player.Player(NetworkElement)");
		position = ne;
		stuck = false;
		stuckTimeLeft = 0;
		inventory = new Inventory(this);
	}

	/** */
	public NetworkElement getPosition() {
		Proto.print("Player.getPosition()");
		return this.position;
	}

	/** */
	public void setPosition(NetworkElement ne) {
		Proto.print("Player.setPosition()");
		this.position = ne;
	}

	/** */
	public boolean getStuck() {
		Proto.print("Player.getStuck()");
		return this.stuck;
	}

	/** */
	public void setStuck(boolean b) {
		Proto.print("Player.setStuck()");
		this.stuck  = b;
	}

	/** */
	public int getStuckTimeLeft() {
		Proto.print("Player.getStuckTimeLeft()");
		return this.stuckTimeLeft;
	}

	/** */
	public void setStuckTimeLeft(int i) {
		Proto.print("Player.setStuckTimeLeft()");
		this.stuckTimeLeft = i;
	}

	/** */
	public Inventory getInventory() {
		Proto.print("Player.getInventory()");
		return this.inventory;
	}

	/** */
	public void setInventory(Inventory inv) {
		Proto.print("Player.setInventory()");
		this.inventory = inv;
	}

	/** */
	public abstract void takePump(Inventory inv);

	/** */
	public abstract void placePump();

	/** */
	public abstract void connectPipe();

	/** */
	public abstract void disconnectPipe(NetworkElement ne);

	public void tick(){
		Proto.print("Player.tick()");
		if (stuck){
			stuckTimeLeft--;
			if (stuckTimeLeft <= 0){
				stuck = false;
			}
		}
	}

	//TODO
	public void move(NetworkElement ne) {
		Proto.print("Player.move()");
		if (ne.accept(this)){
			this.setPosition(ne);
		}
	}
	
	/** */
	public void directPump(Pump pump, NetworkElement in, NetworkElement out) {
		Proto.print("Player.directPump()");
		position.direct(in, out);
	}

	public void makePipeSticky(Pipe p){
		Proto.print("Player.makePipeSSticky()");
		p.setSticky(true);
	}

	public void breakPipe(Pipe p){
		Proto.print("Player.breakPipe()");
		p.breakPipe();
	}
}
